apiVersion: v1
datasources:
  - name: InfluxDB
    type: influxdb
    isDefault: true
    access: proxy
    database: telegraf
    user: tvan-cit
    password: thisisworking
    url: http://influxdb-svc:8086
    jsonData:
      httpMode: GET